wandb_version: 1

Batch_size:
  desc: null
  value: 1024
DataAugmentation_types:
  desc: null
  value: SimCLR_Inception_style_Croping
Dataset:
  desc: null
  value: ImageNet1k
Epochs:
  desc: null
  value: 50
IMG_SIZE:
  desc: null
  value: 224
Learning_rate:
  desc: null
  value: 0.3
Loss type:
  desc: null
  value: contrastive_supervised
Model_Arch:
  desc: null
  value: ResNet50
Optimizer:
  desc: null
  value: LARSW
SEED:
  desc: null
  value: 26
Temperature:
  desc: null
  value: 0.1
Training mode:
  desc: null
  value: SSL
_wandb:
  desc: null
  value:
    cli_version: 0.12.6
    code_path: code/run_single_machine_baseline.py
    framework: keras
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.10
    start_time: 1637719981
    t:
      1:
      - 2
      - 3
      3:
      - 16
      4: 3.8.10
      5: 0.12.6
      8:
      - 5
loss_version:
  desc: null
  value: loss_v0
